class ValidError(Exception):
    def __init__(self, errors):
        pass